### ISSUE TITLE
Error: newProject()/Tp Screening unable to add parent suspect list

### ISSUE THREAD

**Issue by PiaSchuenemann** [rickhelmus/patRoon#100]
Hi,

I am trying to use your transformation product screening option. If i write a small parent suspect list manually the screening afterwards is working. 

parents <- data.frame(name = c("6PPD"),
                      SMILES = c("CC(C)CC(C)NC1=CC=C(C=C1)NC2=CC=CC=C2"),
                      formula = c("C18H24N2")) 

If I am trying to use the same information in a csv file and upload it in newProject()/TP SCreening/Parent suspect list I get an error:

failed to open/parse selected csv file

Does the csv file have to fulfill a certain format? I have tried various things and also exported my manually created table as a csv. But even this cannot be used via the newProject() function.

Thanks
Pia

**Comment by rickhelmus** [comment]
Hi Pia,

The CSV file should just follow the format as your `data.frame` example. Perhaps you could share the file? If you created the file with Excel, it sometimes makes a mess out of it ;-)

**Comment by PiaSchuenemann** [comment]
[data_parents.csv](https://github.com/rickhelmus/patRoon/files/14164888/data_parents.csv)

The csv file containts the same informations as the `data.frame`.

**Comment by rickhelmus** [comment]
Hi Pia,

The file seems to work fine for me. Which version of patRoon do you have installed?

**Comment by PiaSchuenemann** [comment]
Hi Rick,

You said the file is okay. Therefore I tested it on a different computer and it worked completly fine. We found out that it was a problem with the access permissions on my computer to certain directories. When the file is saved on the desktop, everything works. Also when R is run as administrator. We are currently fixing the problem. 

Thank you for your quick reply.
Pia

**Comment by rickhelmus** [comment]
Hi Pia,

Good to hear you are progressing to find a solution. For now I will close this issue, but feel free to re-open if you think it's needed.

Thanks,
Rick
