### ISSUE TITLE
Handbook: Inconsistency for labelled Isotopes

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#101]
Hi Rick,

reading through the [handbook 8.2.1.2](https://rickhelmus.github.io/patRoon/handbook_bd/fNorm.html#internal-standard-normalization)  I found an inconsistency in the specification of isotopes.

> #> 5       Climbazole-D4 C15[2]H4H13ClN2O2 359.1
> As can be seen from above, labelled isotopes can be specified with square brackets, e.g. [2H] for deuterium.

In the `patRoonData::ISTDListPos` (and also `patRoonData::ISTDListNeg`), the square brackets are around the mass number only, in the text below also around the respective symbol.

Kind regards,

Leon

The underlying vignette:
https://github.com/rickhelmus/patRoon/blob/504dc625232d9f5c1948a130dbda6984702e8d72/vignettes/handbook/advanced.Rmd#L84-L88

**Comment by rickhelmus** [comment]
Hi Leon,

Thanks, spot on! What is in the suspect lists is correct.

Thanks,
Rick
