### ISSUE TITLE
Suggestion: 'conc'-column in newProject()

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#102]
Hi Rick,

for [feature regression analysis](https://rickhelmus.github.io/patRoon/handbook_bd/feature-regression-analysis.html#feature-regression-analysis), a `conc`-column is needed in the `analysisInfo`, however there is no possibility to add this information in the `newProject()`-GUI. I'm creating a PR to add this functionality.

Related to this issue: 
I find it a bit confusing, that `generateAnalysisInfo` takes _e.g. norm_concs, concs_ as arguments i.e. the plural of the resulting columns _norm_conc_ and _conc_ in the returned `data.frame`. 

This discrepancy can also be found in the handbook for [feature regression analysis](https://rickhelmus.github.io/patRoon/handbook_bd/feature-regression-analysis.html#feature-regression-analysis):

> ...The conditions are specified in the `conc` column of the analysis information, for instance:
> 
```R
# obtain analysis information as usual, but add some experimental parameters of interest (dilution, time etc).
# The blanks are set to NA, whereas the standards are set to increasing levels.

 anaInfo <- generateAnalysisInfo(paths = patRoonData::exampleDataPath(),
                                 groups = c(rep("solvent", 3), rep("standard", 3)),
                                 blanks = "solvent",
                                 concs = c(NA, NA, NA, 1, 2, 3))
```
> If no experimental conditions are available for a particular analysis then the `conc` value should be NA...

Personally, I would prefer, if the arguments to `genrateAnalysisInfo` would be equal to the resulting columns.

Kind regards,

Leon

**Comment by rickhelmus** [comment]
PR merged!
