### ISSUE TITLE
Using data processing code with already annotated csv file 

### ISSUE THREAD

**Issue by VR-13** [rickhelmus/patRoon#105]
Hi,

I'm working with an untargeted metabolomics dataset that was obtained with mass spectrometry, but I'm new to this analysis so a bit unsure as to how to best process it. I saw your repository and I'm very impressed with the complete pipeline, so I'd like to use it to further process my data! The data has already been processed in MetaboScape and is thus already annotated with molecular formulas as far as possible and currently consists of a single CSV file with samples and their (mostly) annotated metabolite peak intensities. Is there an easy way to use the clustering, visual inspection and analysis of your code with an already processed file or should it be in a different format for this? 

Thanks in advance!

**Comment by rickhelmus** [comment]
Closing this as we discussed it via email.
