### ISSUE TITLE
Warning message during run of findFeatures

### ISSUE THREAD

**Issue by tsufz** [rickhelmus/patRoon#11]
Hi Rick,
While running fList <- findFeatures(anaInfo, "xcms3", verbose = TRUE, param = xset), this warnings show up. I guess it originates  from the parallel run. You may check the run call. Obviously stats needs to be called explicitly for each node.

Best,
Tobias

Warning messages:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con) :
  'package:stats' may not be available when loading
3: In serialize(data, node$con) :
  'package:stats' may not be available when loading
4: In serialize(data, node$con) :
  'package:stats' may not be available when loading
5: In serialize(data, node$con) :
  'package:stats' may not be available when loading
6: In serialize(data, node$con) :
  'package:stats' may not be available when loading
7: In serialize(data, node$con) :
  'package:stats' may not be available when loading

**Comment by rickhelmus** [comment]
Hi Tobias,

I'm pretty sure this originates from `XCMS`, as `patRoon` doesn't use `parallel` itself and simply calls the `XCMS` functions. Would you mind getting in touch with the `XCMS` devs? However, I do think this message is fairly innocent.

Thanks,
Rick

**Comment by tsufz** [comment]
Hi Rick,
I opened an issue in [xcms](https://github.com/sneumann/xcms/issues/499).

Best,
Tobias

**Comment by rickhelmus** [comment]
Hi Tobias,

Thanks! Closing the issue for now, but feel free to re-open if you think that's necessary.
