### ISSUE TITLE
findFeatures Error - Error in if (!recentFFM) settings <- c(settings, `-algorithm:epd:masstrace_snr_filtering` = boolToChr(traceSNRFiltering)) :    missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by Theodoralee03** [rickhelmus/patRoon#112]
Dear Rick and Team,

I recently obtained a new workstation, and wish to run patRoon there instead of my original laptop. However, after setting up everything, i keep facing an error while trying to use the findFeatures() function. I even tried using the patRoon demo data, but i also got the same error

`> anaInfo <- patRoonData::exampleAnalysisInfo("positive")
> fList <- findFeatures(anaInfo, "openms")
Verifying if your data is centroided... Done!
Finding features with OpenMS for 6 analyses ...
Error in if (!recentFFM) settings <- c(settings, `-algorithm:epd:masstrace_snr_filtering` = boolToChr(traceSNRFiltering)) : 
  missing value where TRUE/FALSE needed`

Here is a summary of what I have tried:
1. Updating and reinstalling patRoon, all its dependencies, even external dependencies (These files are stored on my C Drive)
2. Uninstalling R and R Studio 
3. Tried using similar R and R Studio versions as my old laptop, but some patRoon functions were not compatible with the older versions of R, even so, i still had the same error

I have been successful using patRoon before on my old laptop - R Version R-4.2.2 and R Studio 2022.12.0 Version. The current version of R on my new workstation is R-4.4.0 and R Studio 2024.04.2.

I have also tried looking for the log/openMS folder for more information, but somehow it doesn't exist in this new workstation. I have tried ways to create and redirect the error log by creating a new folder using sink(), but the log obtained was not very helpful. Example of the log output 

`Verifying if your data is centroided... Done!
Finding features with OpenMS for 6 analyses ...`

Do you have any advice on what else I can try to rectify this error? 

Thank you so much!

Sincerely,
Theo

**Comment by rickhelmus** [comment]
Hi Theo,

Strange...! It seems an internal function fails that is supposed to figure out your OpenMS version. Would you be able to run the following and tell me its output:

```r
patRoon:::executeCommand(patRoon:::getExtDepPath("openms", "FeatureFinderMetabo"), stdout = TRUE, stderr = TRUE)
```

Thanks,
Rick

**Comment by Theodoralee03** [comment]
Hi Rick,

Here is the output

`> patRoon:::executeCommand(patRoon:::getExtDepPath("openms", "FeatureFinderMetabo"), stdout = TRUE, stderr = TRUE)
character(0)
attr(,"status")
[1] 309
Warning message:
In system2(cmd, sapply(args, shQuote), ...) :
  running command '"C:/Users/arole/AppData/Local/R/win-library/4.4/patRoonExt/ext/openms/bin/FeatureFinderMetabo.exe"' had status 309`

Thank you!

**Comment by Theodoralee03** [comment]
Hi Rick,

I have found a solution. After what you've mentioned, I was wondering if it could be to do some dependency files that were missing and could not support OpenMS in patRoon

I downloaded OpenMS at https://abibuilder.cs.uni-tuebingen.de/archive/openms/OpenMSInstaller/release/latest/ 
That had managed to resolve my issue.

Thank you!

**Comment by rickhelmus** [comment]
Hi @Theodoralee03 ,

Sorry for the slow response. But I am happy to see you could fix the issue yourself! In the end it turned out that some DLLs were missing in the bundled OpenMS and OpenBabel files from `patRoonExt`. This should be fixed now.

Thanks,
Rick
