### ISSUE TITLE
Problem getting started

### ISSUE THREAD

**Issue by janajohansson** [rickhelmus/patRoon#13]
Hi! I have tried to follow your tutorial using the example data package. After filling in the specified settings in the dialogue box that appears after typing in newProject() and clicking "create", Rstudio opens a new window which is empty apart from some standard text on Rstudio (and the window I worked in disappears). I suppose that what is supposed to happen is that there is something to work with in that new window. Do you know why this happens? I have made sure that I have downloaded the example data package. When I launch patROON I get a message saying that "mzR has been built against a different Rcpp version". I do have the latest verion of mzR. I also tried uninstalling and reinstalling it. In doing this, I got the message "Installation path not writeable, unable to update packages: survival". I got the same message when trying to upgrade the bioconductor installation.

**Comment by rickhelmus** [comment]
Hello,

Thanks for your interest in `patRoon`. It seems everything is working fine! The warning about `mzR` you can perfectly ignore. The 'empty rstudio window' is what you want. The next step is to open the `process.R` file in the project directory.

Maybe I am mistaken, but it sounds to me that you are new to R and rstudio, I would suggest to follow some of the many tutorials that are available on the web to get familiar with the basics.
