### ISSUE TITLE
Installation of patRoon fails

### ISSUE THREAD

**Issue by pvervliet** [rickhelmus/patRoon#2]
After installing all dependencies I get the following error when trying to install patRoon from GitHub:

> install_github("rickhelmus/patRoon", dependencies=TRUE)
Downloading GitHub repo rickhelmus/patRoon@master
from URL https://api.github.com/repos/rickhelmus/patRoon/zipball/master
Installing patRoon
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/PVervliet/AppData/Local/Temp/RtmpMbGbTI/devtools212c51554616/rickhelmus-patRoon-87692e7"  \
  --library="C:/Users/PVervliet/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'patRoon' ...
** libs
  running 'src/Makefile.win' ...
g++    -c -o GenForm-svn/main.o GenForm-svn/main.cpp
make: g++: Command not found
make: *** [<builtin>: GenForm-svn/main.o] Error 127
Warning: running command 'make --no-print-directory -f "Makefile.win"' had status 2
ERROR: compilation failed for package 'patRoon'
* removing 'C:/Users/PVervliet/Documents/R/win-library/3.3/patRoon'
Installation failed: Command failed (1)

I already reinstalled Rtools to be sure but the error keeps showing up.

**Comment by rickhelmus** [comment]
Hello,

Did you make sure that Rtools added its binary to PATH? I'm not yet exactly sure why this happens, but I recently noticed that adding the location manually may provide a suitable workaround. For instance, I added the location "C:\Rtools\mingw_64\bin" to the user's PATH environment variable. I guess doing so using `Sys.setenv()` in your script can also work.

Please let me know in case you have any doubts.

**Comment by pvervliet** [comment]
I checked the PATH and Rtools bin was present.
However, adding the location "C:\Rtools\mingw_64\bin" did solve the problem and I could install the patRoon package.

Thank you!
