### ISSUE TITLE
xcms3 optimizeFeatureFinding requires pre-loading library(xcms)

### ISSUE THREAD

**Issue by tew42** [rickhelmus/patRoon#21]
Hi, I've been using your library (with xcms algorithm) for a while now and have appreciated the available workflows! Now I recently tried to "upgrade" my pipeline to xcms3 algorithm instead, but my workflow fails at the Feature Finding Optimization. 

Details (this is in R4.0.3):
* library(patRoon)
* create analysisInfo (e.g. for sample data set)
* paramsPP <- generateFeatureOptPSet('xcms3')
* ftOpt <- optimizeFeatureFinding(anaInfo, 'xcms3', paramsPP)

Expected output: 
optimized parameters

Actual output:
"error in evaluating the argument 'X' in selecting a method for function 'bplapply': could not find function "featureData" "

To fix:
* library(xcms)
[after loading patRoon]

**Comment by rickhelmus** [comment]
Hello,

Thanks for the report! This seems to be related to https://github.com/rickhelmus/patRoon/issues/16 and should be fixed by updating to the newest `MSnbase`. Could you see if that also works for you?

Thanks,
Rick

**Comment by tew42** [comment]
Indeed that's a **duplicate**. Sorry about that, I forgot to check the closed issues

**Comment by tew42** [comment]
Thanks for getting back to me, indeed that's a **duplicate**. Sorry about that, I forgot to check the closed issues. And yes, updating MSnbase fixes things!
