### ISSUE TITLE
issue with matchedFilter (another small xcms3 optimization bug)

### ISSUE THREAD

**Issue by tew42** [rickhelmus/patRoon#23]
Hi again,

I just noticed that congratulations are in order for your publication!

Anyway, similar to my attempt at switching to peakgroups (thanks for the rapid fix!) I'm now also giving matchedFilter a go. It seems that the variable names there need an update:
generateFeatureOptPSet() generates a set containing the parameter "step", which is not recognized by xcms. The correct name should now be "binSize", I believe.

**Comment by rickhelmus** [comment]
Many thanks! Yes, glad the paper is out there now :-)

Thanks again for the bug report. I pushed the fixed among some other small optimization related fixes.
