### ISSUE TITLE
Potential bug in optimizeFeatureGrouping of XCMS3 parameters

### ISSUE THREAD

**Issue by coltonlloyd** [rickhelmus/patRoon#27]
Hi Rick,

Thank you for creating this excellent pipeline for nontargeted metabolomics analysis. 

I have been using the IPO implementation to optimize feature grouping parameters in xcms3 (via `optimizeFeatureGrouping`), and have run into issues when optimizing `binSize` and `minFraction` when `groupMethod='density'`. It appears that these values are rounded which causes an error when `binSize` is rounded down to 0 (see output below).

![image](https://user-images.githubusercontent.com/6590204/116754358-731b1580-a9bd-11eb-8b4f-920542ea28e1.png)

Is it possible that this line of code is causing the issue?

https://github.com/rickhelmus/patRoon/blob/c57a76678f02d7c5fb1872487129423527740b50/R/feature_groups-optimize-xcms3.R#L72

Thanks again,
Colton

**Comment by rickhelmus** [comment]
Hi Colton,

Many thanks for the bug report. It seems there was a small error when converting from the classic `XCMS` interface to the new one. It should be fixed now.

Thanks,
Rick
