### ISSUE TITLE
small typo in the install script

### ISSUE THREAD

**Issue by mrtbru** [rickhelmus/patRoon#28]
Hello Rick,

today i installed patRoon on a new machine using the automatic windows install script. The script fails at some point because of a typo in line 558:

                    # place in jar from patRoonDeps
                    jar <- downloadFile(file.path(dow, "biotransformer"), "BioTransformer jar",
                                        "https://github.com/rickhelmus/patRoonDeps/raw/master/ext/biotransformer-3.0.0.jar",
                                        FALSE)

it says "dow", when it should be "down". Changing that allows the script to finish.

Regards,

Martin

**Comment by rickhelmus** [comment]
Hi Martin,

Thanks for the report! Should be fixed now.
