### ISSUE TITLE
gsub: invalid regular expression '\', 

### ISSUE THREAD

**Issue by diasmandala** [rickhelmus/patRoon#3]
Dear Rick Helmus,

I am a beginner using patRoon, i want to exercise processing MS data with this.

when i tried making new project, this message came 

Warning: Error in gsub: invalid regular expression '\', reason 'Trailing backslash'

Would you explain me ?

best regards,

**Comment by rickhelmus** [comment]
Hello,

Thanks for your bug report.

I recently (copuple of days ago) pushed a fix for this. Can you try it again after updating to the newest git version, i.e. by re-running `install_github`?

Thanks,
Rick

**Comment by rickhelmus** [comment]
Seems it's fixed from #4. Closing this.
