### ISSUE TITLE
[JOSS Review] `generateAnalysisInfo` function parameters documentation

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#33]
The documentation for this function is quite confusing. First of all, I think the term `analysis` to describe individual samples here is a bit misleading. It is also stated that `path` should be a filepath - it should actually be a path to the directory containing the data.

**Comment by rickhelmus** [comment]
I just committed some improvements to the documentation for the _analysis information_. I think this documentation page was one of the first in `patRoon`, so I also took the liberty to put in other improvements ;-) The parameter/argument descripts should be better now, and I clarified what an _analysis_ means with `patRoon`. Perhaps in hindsight a _sample_, _MS analysis_ or something else could be a better term, however, changing this would mean **extensive** changes throughout all the code and documentation, break compatibility with older scripts and potentially introduce bugs that need to be fixed. Furthermore, I have seen the term _analysis_ popping up in other software tools too, such as our vendor software. Hence, I prefer to stick with the _analysis_ terminology.
