### ISSUE TITLE
[JOSS Review] Make file extension for supported MS file types case insensitive

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#34]
`generateAnalysisInfo` finds `mzML` files but no `mzml` files, which can be impractical if working with large read-only file storage.

Seems like it starts to collect everything at first and then `filterMSFileDirs` actually filters case sensitive for the extensions again, so they are removed.

https://github.com/rickhelmus/patRoon/blob/b0bffbabe5605579ba8781b24336e95895c7e15c/R/convert.R#L86-L95

**Comment by rickhelmus** [comment]
Thanks for the suggestion and little investigation :-) Should be fixed now!
