### ISSUE TITLE
[JOSS Review] BUG: `groupFeaturesKPIC2` fails after `findFeaturesXCMS` if `loadRawData = TRUE`

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#36]
I used patRoon via the docker image and used 12 profile LC-ESI+-MS1 mzML files, then ran feature detection using XCMS and tried to group features via KPIC2 and got the error listed in the log below.

After rerunning with `centWave` as explicit method and adding group information to the analysis I get the following error:
```
> groups_kpic2_retry <- patRoon::groupFeaturesKPIC2(features)
Grouping features with KPIC2... Error in rep(0, curdiff) : invalid 'times' argument
```

[bug_report.txt](https://github.com/rickhelmus/patRoon/files/7822132/bug_report.txt)

**Comment by rickhelmus** [comment]
Hi @hechth,

Nearly all of the algorithms implemented or interfaced in `patRoon` expect centroided data. `KPIC2` is one of them, and as far as I am aware `XCMS` also expects it.  Would you be able to re-run it with centroided data?

In the mean while I will clarify this better in the documentation and see if I can add some input data checks to notify the user.

**Comment by rickhelmus** [comment]
The commits referenced above add code to verify that MS data is centroided and some additional notes to the documentation.

**Comment by hechth** [comment]
I'll check with centroiding the data before whether this works then, thanks for the hints!

**Comment by rickhelmus** [comment]
Hmm... I am afraid this might be a bug in `KPIC2` [during RT alignment](https://github.com/hcji/KPIC2/blob/091a20f4ed9f0fdec18c8de9b35fc429024fc66a/R/PICalign.R#L102). If you could share a few  MS files that trigger this I could try to take a look what is going on and try add a fix to [my fork](https://github.com/rickhelmus/KPIC2). I guess if you set `rtalign=FALSE` to `groupFeatures()` the error will go away.

**Comment by hechth** [comment]
I'll try - I also tried I think finding the features with KPIC but it just seems to be computing forever and gets stuck on 0%.

I can send you more details, but these problems are very likely related to the underlying algorithm, not patRoon itself.

I can play around with it a bit more and create some `minimal working example` where the error occurs. Thanks for looking into this!

**Comment by hechth** [comment]
Yeah, it works with `rtalign=FALSE`.
