### ISSUE TITLE
[JOSS Review] Handbook `single page` and `book format` don't match

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#39]
The [book format](https://rickhelmus.github.io/patRoon/handbook_bd/index.html) version and [single page](https://rickhelmus.github.io/patRoon/articles/handbook.html#advanced-usage) version of the handbook contain different information, i.e the single-page version has no information regarding the transformation products. Maybe it would be better to keep only the `Tutorial` section and the `book format` pages updated and focus on those instead of having somewhat duplicate but similar information?

**Comment by rickhelmus** [comment]
Yes, I agree it might be better to leave it out (just comitted, will take a bit for CI to catch up). To be honest I don't really remember if there was a strong reason for me to have the single page version, but I think it was more a 'nice to have' as it could be done fairly easy with `pkgdown`. Anyway, this issue proves that it can become a small maintenance burden so I took it out.

**Comment by hechth** [comment]
I think it will be easier to maintain like this, with a dedicated tutorial section, the real handbook (so a mixture of API documentation and tutorial) and the purely auto generated API docs.
