### ISSUE TITLE
[JOSS Review] Update overview graphics

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#41]
The main diagram showing the workflows could be extended with something closer to the code, showing the individual operations and data flow. I thought about something like this. If you agree, I can share the document and we can make a refined version of this, maybe also including links to the actual function documentation etc.

![image](https://user-images.githubusercontent.com/12066490/148528689-cba96f64-a1e3-4184-b08a-bebe88dc40e5.png)

**Comment by rickhelmus** [comment]
Hi @hechth 

Many thanks for this diagram and also for the other feedback! The diagram looks very clear and definitely something I would like to include. I just returned from Holidays and still catching up... but hopefully I can work on the issues and give a more thorough look at the scheme later this week. 

Thanks,
Rick

**Comment by hechth** [comment]
Hi Rick,

sure, take your time -,and please don't feel overloaded given the number of issues etc. I created - most of them are very minor things. I will also need a bit more time to finish the review - just reach out if something is not clear or you'd like some support from my side with certain things.

Best, Helge

**Comment by hechth** [comment]
I created the graphics using draw.io - I attached the file I posted above as an XML, I think you should be able to import it (under Import -> Device) and make changes. If this doesn't work I'll send you a link with the shared document from GoogleDrive via email.
[patroon.zip](https://github.com/rickhelmus/patRoon/files/7976514/patroon.zip)

**Comment by rickhelmus** [comment]
Thanks! The import works.

To include URL links and to (hopefully) make it more easy to maintain I started experimenting with `graphViz`

![image](https://user-images.githubusercontent.com/37015911/152388229-506cf507-3046-42c4-aa03-61d1e0b2f220.png)

Not quite there yet... the layout with so many connections is particularly tricky.

**Comment by rickhelmus** [comment]
More progress!

![image](https://user-images.githubusercontent.com/37015911/153025058-2027921e-d884-46ec-b492-029247159a88.png)

Next step is auto URL linking :-)

**Comment by rickhelmus** [comment]
Alright, the URL links are now in and after some more tweaks the graph is now [in the Handbook](https://rickhelmus.github.io/patRoon/handbook_bd/introduction-1.html#overview-of-all-functions-and-their-output).

**Comment by hechth** [comment]
This is amazing!
