### ISSUE TITLE
[JOSS Review] BUG: Can't centroid `mzml` data using `convertMSFiles`

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#42]
To centroid existing `mzml` files, the `convertMSFiles` function could be used (I assume). The problem is that the function throws an exception if the conversion doesn't change the format but does only the centroiding. Maybe a dedicated centroiding function or lifting this restriction on changing the format could also do the trick?

**Comment by rickhelmus** [comment]
Hi,

By coincidence I actually lifted this restriction last week ([commit](https://github.com/rickhelmus/patRoon/commit/4da9894b895cad47786fb81cd235e2e2e502f128)).

**Comment by hechth** [comment]
Hm - I think I updated and used a new version - maybe the docker image didn't get updated correctly? Also can be that I didn't manage to get the latest version, I'll retry. Thanks for letting me know!

**Comment by rickhelmus** [comment]
Hmm strange...

I recently added 'conversion' from mzXML to mzXML as a workaround in [the unit tests](https://github.com/rickhelmus/patRoon/blob/master/tests/testthat/helper_utils.R#L207). So I would expect it to work.

PS: don't forget to set `overWrite=TRUE` as otherwise nothing will happen... :-)

**Comment by hechth** [comment]
Well can I also store the data somewhere else? I don't necessarily want to overwrite my profile data with centroids.

**Comment by hechth** [comment]
Ah so this doesn't work in the docker image as it doesn't come with pwiz installed, right?

**Comment by rickhelmus** [comment]
Ah yes, sorry I completely forgot about that. Unfortunately including ProteoWizard is difficult due to licensing issues AFAIK.

**Comment by hechth** [comment]
okay so centroiding mzml seems to be quite non trivial. I'll upload some centroided data then and retry.
