### ISSUE TITLE
[JOSS Review] Bug: `findFeaturesSIRIUS(...)` fails

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#45]
When trying to detect features on centroided data (`findFeaturesXCMS` works fine), I get the following error message.

The files are LC-MS1 files from orbitrap - is it possible that SIRIUS always expects MS2 data to be present?

```
r$> features <- findFeaturesSIRIUS(info)
Verifying if your data is centroided...
Finding features with SIRIUS for 12 analyses ...
  |=================                                                                                                                                                                                            |   8%Error in setorderv(ret, "mz") : 
  some columns are not in the data.table: mz
In addition: Warning message:
call dbDisconnect() when finished working with a connection 
```

**Comment by rickhelmus** [comment]
> is it possible that SIRIUS always expects MS2 data to be present?

Yep! DDA MS/MS to be exact.

I will add a note to the reference docs.

**Comment by hechth** [comment]
Thank you very much, I think the note might be helpful :).
