### ISSUE TITLE
[JOSS Review] Bug: `findFeaturesXCMS` and `findFeaturesXCMS3` fail on Windows

### ISSUE THREAD

**Issue by hechth** [rickhelmus/patRoon#46]
Finding features with XCMS fails on windows since BiocParallel can't be easily installed on Windows with a default R version - only some combinations work apparently. XCMS requires BiocParallel to be installed, so fails if not.

```
r$> features <- findFeaturesXCMS(centroid)
Verifying if your data is centroided...
Finding features with XCMS for 12 analyses ...
Error in loadNamespace(name) : there is no package called 'BiocParallel'
Calls: local ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
```

XCMS3 fails also for some other reason - see the log below.

```
r$> features <- findFeaturesXCMS3(centroid)
Verifying if your data is centroided...
Finding features with XCMS for 12 analyses ...
Loading raw data...
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'bplapply': could not find function "featureData"
```

**Comment by rickhelmus** [comment]
Hi,

> Finding features with XCMS fails on windows since BiocParallel can't be easily installed on Windows with a default R version - only some combinations work apparently. XCMS requires BiocParallel to be installed, so fails if not.

With the last R version (4.1.2) and BioConductor (3.14) it works fine on my laptop, both CIs and I just tried it on a fresh Windows VM.

In any case, these errors seem related from `BiocParallel` and `xcms`, so perhaps better to check with them?

> XCMS3 fails also for some other reason - see the log below.

And this is possibly related to #16? Again not really under my control ... :-/
