### ISSUE TITLE
Dependency broken - off CRAN

### ISSUE THREAD

**Issue by wesleyburr** [rickhelmus/patRoon#48]
As of Feb 25, 2022, **nontarget** is no longer available from CRAN, which means patRoon cannot be installed on non-Windows installations of R; and only on Windows if the miniCRAN repository keeps an archived version of nontarget handy. 

So I guess figure out how critical this package is, and either strip it, or embed it? Sorry to be a moving target, but dependency hell is the worst thing about the R package ecosystem.

**Comment by wesleyburr** [comment]
It looks like nontarget and its dep, nontargetData, both still install fine, they just started failing CRAN checks. So you could probably just extract them from the CRAN archive, and make them available. It'll need a custom note in the installation process, though - or just strip out the dependency and embed whatever functionality was needed from the package locally?

**Comment by rickhelmus** [comment]
Hi @wesleyburr 

Thanks for the report! It's a pity `nontarget` was recently removed. For now, I made this an optional dependency and the documentation, CI and package repository all now all link to GitHub repository for both `nontarget`/`nontargetData` (see the linked commits above). Luckily the package is only used for a specific algorithm so I think it should be fine like this.

Thanks,
Rick
