### ISSUE TITLE
patRoon does not contain enviMass

### ISSUE THREAD

**Issue by blosloos** [rickhelmus/patRoon#5]
Please remove the enviMass web link from your github package description: the described "grouping of features" (= profiling of peaks of similar mass/RT over different files) has recently been confused by users with the componentization step of enviMass (which patRoon takes from our nontarget package); and even the extraction and grouping of features from enviMass can only partly be embedded in patRoon or other workflows. Thus, providing the impression that patRoon harmonizes or contains any version of enviMass is pretty misleading; the more as there are lots of enviMass features which cannot be embedded in other workflows out of their specific enviMass workflow context that easily and without risks. Thanks for your understanding!

**Comment by rickhelmus** [comment]
Hello,

I am sorry to hear that this led to some confusion! I tried to clarify the current situation a bit better 
 ([see commit](https://github.com/rickhelmus/patRoon/commit/bbd342aa09d04e902a9355eb9b719a41e8ebe6e2)). Please let me know if you think this is sufficiently clear now.

I also removed the mentioning of `enviMass` from the `README` - the current support is based on an older version that was still on GitHub (which I cannot install anymore) and I'm not actually sure if it still works with the latest enviMass. It would be really great if this could be updated and improved some day - if you are open to this of course.

Thanks,
Rick

**Comment by blosloos** [comment]
Hi Rick - Thanks for your understanding & the commit; I hope you don`t perceive my concerns as too strict or haughty. enviMass has become a bit more closed - as far as this is possible/desirable with partly GPL-licensed software; the reason being that the commercial side of the distribution has to finance the workflow development now. And this in turn supports some of the underlying and fully open packages as well (nontarget, enviPick, enviPat). Have a good 2019, Martin

**Comment by rickhelmus** [comment]
Hi Martin,

Thanks for your clarification, the situation is definitely understandable.

Best of luck and have a good 2019 as well!
