### ISSUE TITLE
FindFeatures issue with example data

### ISSUE THREAD

**Issue by kbrigit** [rickhelmus/patRoon#50]
Hi, 

I am just trying to follow the patRoon tutorial and keep getting the following error (below) when I run "findFeatures" with the patRoon example data. Have I loaded something in wrong? What might be causing this error? I am pretty new to patRoon and R, so any help is greatly appreciated! Thanks.

 fList <- findFeatures(anaInfo, "openms", noiseThrInt = 1000, chromSNR = 3, chromFWHM = 5, minFWHM = 1, maxFWHM = 30)
Verifying if your data is centroided...
Finding features with OpenMS for 6 analyses ...
  |                                                                                                                           |   0%Error in maybeRestartCommand(commandQueue[cmdInds], runningProcInfo[[pi]],  : 
  Failed to run command 'C:/Program Files/OpenMS/bin/FeatureFinderMetabo.exe' with args: '-algorithm:common:noise_threshold_int 1000 -algorithm:common:chrom_peak_snr 3 -algorithm:common:chrom_fwhm 5 -algorithm:mtd:mass_error_ppm 10 -algorithm:mtd:reestimate_mt_sd true -algorithm:mtd:trace_termination_criterion sample_rate -algorithm:mtd:trace_termination_outliers 5 -algorithm:mtd:min_sample_rate 0.5 -algorithm:mtd:min_trace_length 3 -algorithm:mtd:max_trace_length -1 -algorithm:epd:width_filtering fixed -algorithm:epd:min_fwhm 1 -algorithm:epd:max_fwhm 30 -algorithm:ffm:local_rt_range 10 -algorithm:ffm:local_mz_range 6.5 -algorithm:ffm:isotope_filtering_model metabolites (5% RMS) -algorithm:ffm:mz_scoring_13C false -algorithm:ffm:use_smoothed_intensities true -algorithm:ffm:report_convex_hulls true -algorithm:epd:masstrace_snr_filtering false -in C:\Users\AppData\Local\R\win-library\4.2\patRoonData\extdata\pos/solvent-pos-1.mzML -out C:\Users\AppData\Local\Te

**Comment by rickhelmus** [comment]
Hi @kbrigit ,

It seems OpenMS has troubles running on your system. Hopefully you can find more details in one the log files inside the  `log/openms` directory inside your project directory. Could you check the text files for any further error messages?

Thanks,
Rick

**Comment by rickhelmus** [comment]
Closing this old issue because of inactivity.
