### ISSUE TITLE
Linking parents and TPs... Error generating the `precursor` object

### ISSUE THREAD

**Issue by chirsir** [rickhelmus/patRoon#51]
Hi,

I hope I can get some help with this.

I've been trying to run Non-target screening of predicted TPs. when I run this part of the code adapted from the example workflows (from example 7.3.3 in the handbook):
 step 4
`suspects <- convertToSuspects(TPs)`  

`fGroupsScr <- screenSuspects(fGroups, suspects, adduct = "[M-H]-", onlyHits = FALSE)`  

step 5
` componTP <- generateComponents(fGroupsScr, "tp", TPs = TPs, MSPeakLists = mslists, formulas = formulas)`
I get this Error :
` in (function (spec, gn, ana)  : object 'precursor' not found`
I believe the code in step 4 was supposed to generate this object `precursor` but it didn't. but step 4 ran without any errors

**Comment by rickhelmus** [comment]
I guess this is fixed, so closing the issue...
