### ISSUE TITLE
screenSuspects fatal error

### ISSUE THREAD

**Issue by rachsmo** [rickhelmus/patRoon#52]
Hello, 
I have been trying to screen suspects with patRoon using the default list, my own suspect screening list, and code from the written tutorial. It seems that every time I run screenSuspects( ) function I run into a fatal error and have to start over. Unfortunately, this also means there is nothing in the error log regarding the issue. 
Best, 
Rachel

**Comment by rachsmo** [comment]
I just want to add that this also happens with generateFormluas( ). I have tried running the tutorial code on two different PCs and run into the same issue. Any suggestions are greatly appreciated. This is with 2.1.0.

**Comment by rickhelmus** [comment]
What also might help is to install R 4.2.1, currently it is not yet available but you can install a release candidate: https://cran.r-project.org/bin/windows/base/rpatched.html This resolved some other R crashes I had on a new laptop, perhaps it also solves this problem.

Thanks,
Rick

**Comment by rachsmo** [comment]
Hi Rick, 
Thank you for your reply. Removing JDK/JRE versions didn't seem to work, but reverting back to older versions of R and RStudio solved the issue for me. 
I will also try your suggestion of installing 4.2.1 and see how that goes. 

Thanks again, 
Rachel

**Comment by janb-k** [comment]
Hi Rick,
I had the same issues as Rachel. Both downgrading R to 4.1.0 and upgrading to 4.2.1 fixed them for me without changing something with my JDK/JRE versions. 

Best,
Jan

**Comment by rickhelmus** [comment]
Thanks for your feedback @janb-k !

I will close the issue for now, but feel free to add more details if problems still occur.
