### ISSUE TITLE
MetaClean labels flipped

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#59]
Hi,
I am getting familiar with using **patRoon 2.1.0** inside a Docker container. 
I was trying to use the `predictCheckFeaturesSession` with the `MetaCleanData::example_model`  and when I inspected the prediction results with `checkFeatures`, I noticed that mostly _bad_ features were kept and _good_ features removed fully:

_Example:_ Kept features vs. removed features: 
 ![image](https://user-images.githubusercontent.com/68274160/206210232-6670c03e-e3c1-4b68-a095-4cf0b452ce36.png) vs. ![image](https://user-images.githubusercontent.com/68274160/206210386-e1335508-a725-4a4d-98db-605c8d979f89.png)

In the code the names subset with `c("GOOD", "Pass")` are removed:

https://github.com/rickhelmus/patRoon/blob/d2923b0dc4939895f5aa4cf19ac47298033afa91/R/check_features.R#L469-L470

I think it should be the other way around e.g.:
``` 
rmf <- gNames[preds[preds$Pred_Class %in% c("BAD", "Fail"), "EIC"]] 
saveCheckSession(list(removeFully = rmf, removePartially = list()), session, fGroups[, rmf], "featureGroups")
```
Or have I missed an important part?

Kind regards and thank you for your help!

Leon

**Comment by rickhelmus** [comment]
Hi Leon,

Many thanks for spotting this (silly!) mistake. I think it happened after refactoring some code a while ago. Anyway, it should pick the bad/fail peaks now :-)

Thanks,
Rick
