### ISSUE TITLE
Suggestion: newProject(): Save UI-Input as configuration file

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#61]
Hi,

I thought it might be helpful to save the choices made in the UI to be able to reproduce it at a later point.
To accomplish this, I suggest:

1. save `input` and `analyses`, that get passed to the script-function e.g. as `.rda` or `.yml`
https://github.com/rickhelmus/patRoon/blob/4e04f926a9b000c7eaa8332575a5eb1c462cf72d/R/project-tool.R#L4
2. add option to `newProject()` to load file to set as initial values for the UI for later inspection/alteration

Kind regards

Leon

**Comment by rickhelmus** [comment]
Hi Leon,

Yes, this is definitely a good addition and has been on my TODO list for some time :-)

**Comment by rickhelmus** [comment]
Hi again,

Just pushed this functionality to the master branch. The parameters are stored in `.yml` files. I decided to not include any analyses with the assumption that these will typically change with subsequent project creations.
