### ISSUE TITLE
Question: reporting: Increase resolution of plots

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#64]
Hi Rick,

when I'm using the `reportHTML()` function, the graphs shown under the _Summary_ tab have quite a low resolution. Is there a way to increase it?

Kind regards

Leon

**Comment by rickhelmus** [comment]
Hi Leon,

I am actually improving the reporting now in another branch. One of the improvements is that all plots will be SVG files, which should tackle this issue. It might take a bit for me to finish everything though, so your best bet is to reproduce the plots manually in R for now...

**Comment by rickhelmus** [comment]
Fixed now with the new reporting interface.
