### ISSUE TITLE
Error: Visualization: plotVenn(): diagram cut off

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#65]
Hi Rick,

when I visualize data with `plotVenn()`, the sample labels are cut off for longer group names (13 characters):
![ae4deba9-8741-4610-85d8-2af4a129b5af](https://user-images.githubusercontent.com/68274160/207570515-d0de46cf-cf21-4f04-954a-45d6ee087808.png)

Kind regards

Leon

**Comment by rickhelmus** [comment]
Hi Leon,

Yes this can happen and needs some tweaking with the plotting options that are used by the underlying VennDiagram package. I think the `margin` argument is what you are after. See e.g. `?VennDiagram::draw.pairwise.venn`.

**Comment by rickhelmus** [comment]
Closed due to inactivity, feel free to re-open if needed!
