### ISSUE TITLE
Error: selectIons() - could not find chromPeaks

### ISSUE THREAD

**Issue by LeonSaal** [rickhelmus/patRoon#68]
Hi Rick,

please take a look at the following:

```
> fGroups <- selectIons(fGroups, components, prefAdduct = "[M+H]+", onlyMonoIso = TRUE)
Error in chromPeaks(obj@xdata) : could not find function "chromPeaks"
```

I guess the error is caused by a missing `xcms::` in front of `chromPeaks`, I think here: 
https://github.com/rickhelmus/patRoon/blob/440484dd24522b24f4676d32eb0b2012c9de4165/R/feature_groups-xcms3.R#L214

Kind regards,
Leon

**Comment by rickhelmus** [comment]
Hi Leon,

Many thanks for reporting this and with a fix! :-)
