### ISSUE TITLE
Updated Docker image

### ISSUE THREAD

**Issue by akogler** [rickhelmus/patRoon#70]
Hi Rick,

Is the latest Docker image updated to patRoon v 2.2? I am running patRoon using [this modified singularity file](https://github.com/romxero/patroonOpenmsSingularity/blob/main/Singularity). It has been working without issue until I recently started testing out the sets workflow and ran into the following error during the componentization step:

> Error in .local(fGroups, components, prefAdduct, ...) : No adduct/isotope information available in given components!
> Calls: selectIons ... Map -> mapply -> <Anonymous> -> <Anonymous> -> .local
> Execution halted

This happens when I try to run this command:
`fGroupsSel <- selectIons(fGroups, componOpenMS, c("[M+H]+", "[M-H]-"))`

Based on what I read about changes from patroon v 2.1 to 2.2, it seems like this error may have been fixed and I'm wondering if that update isn't reflected in the Docker image yet because I am pulling the latest Docker image each time. Thank you!

**Comment by rickhelmus** [comment]
Hello,

Thanks for your report. CI was stuck and needed some attention, but a new Docker image should be available now. Hopefully this fixes the problem!

**Comment by akogler** [comment]
Hi Rick,

Thanks for looking into the issue! I see that the Docker image was updated just yesterday but I think it might still be version 2.1 if I am looking in the [correct spot on Docker Hub](https://hub.docker.com/layers/patroonorg/patroonrs/latest/images/sha256-9df670a9db520f075a19a657f61c51f86fd559002dd6bb89c264e0291eb361a1?context=explore) (line 19).
![dockerHub](https://user-images.githubusercontent.com/32507456/220475514-fa44ffd0-662c-4f62-857c-cb4e8af3b2d6.JPG)

When I run patRoon, it indicates that version 2.1.0 is being used. Could you double check if there might still be an issue with the Docker image? Thanks so much!

**Comment by rickhelmus** [comment]
Hello,

I just pulled the latest image and it seems up to date. Note that the version you mention is not from `patRoon`, but from the S6 init system used by the rocker base image.

Are you still observing the issue with `selectIons()`?

**Comment by akogler** [comment]
Hi Rick,
I am still experiencing the same issue with selectIons(). [slurm-14992932.txt](https://github.com/rickhelmus/patRoon/files/11162220/slurm-14992932.txt) is the output file that is generated when I try to run the componentization step during a sets workflow. [This](https://github.com/rickhelmus/patRoon/files/11162370/ComponentizationSets.txt) is the R script that I am trying to run.

When patRoon is initialized in R, the message "Welcome to patRoon 2.1.0" appears. I thought that the latest version of patRoon should be pulled from Docker Hub each time I run a job that uses the singularity file I linked in my first comment. It seems that this isn't actually working. Given that the Docker images moved to a new host, I'm wondering if I need to modify my singularity file?

Based on the code and output I shared above, do you think there might be something causing the error other than the version issue?

Thanks,
Anna

**Comment by rickhelmus** [comment]
Hi Anna,

You are right that the welcome message hints on an older version of patRoon. Unfortunately, I have zero experience with singularity, so I cannot be much of a help with that, sorry... But it seems reasonable to first figure out how to ensure that singularity pulls the latest Docker image, then we can see what to do if you are still facing the issue with componentization.

Thanks,
Rick

**Comment by rickhelmus** [comment]
Closed due to inactivity, feel free to re-open!
