### ISSUE TITLE
Docker: request canceled while waiting for connection

### ISSUE THREAD

**Issue by tellyshia** [rickhelmus/patRoon#75]
Dear Rick,

Thank you for the excellent work you've done on patRoon, and in particular, for providing the docker image - it's been incredibly helpful.

I've noticed a change in the docker image host and I encountered this error message:

```
docker run --rm -it uva-hva.gitlab.host:4567/r.helmus/patroon/patroonrs
Unable to find image 'uva-hva.gitlab.host:4567/r.helmus/patroon/patroonrs:latest' locally
docker: Error response from daemon: Get "https://uva-hva.gitlab.host:4567/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
```

Do I need login credentials to connect to the container registry? Any help or information you can provide would be greatly appreciated.

Thank you for your time and effort.

Best regards,
Lit

**Comment by rickhelmus** [comment]
Hi Lit,

Maybe this was a temporary issue with the host? For me everything seems to work fine, and there should be no login required. If you are still facing the issue, could it be that your network is somehow blocking the connection?

Thanks,
Rick

**Comment by rickhelmus** [comment]
Closed due to inactivity, feel free to re-open!
