### ISSUE TITLE
Error : Failed to run genform

### ISSUE THREAD

**Issue by nina-huynh** [rickhelmus/patRoon#8]
Hello,

I tried to run your app and it worked well until the formula calculation step.
Indeed, I tried this command :

`formulas <- generateFormulas(fGroupsopenms, "genform", plists, maxMzDev = 5,
                             adduct = "[M+H]+", elements = "CHNOPSCl")`

which gives me this error : 

> Error in errorHandler(cmd = commandQueue[[ci]], exitStatus = exitStatus,  : 
  Failed to run command 'C:/Users/167160/Documents/R/R-3.5.3/library/patRoon/bin//x64/GenForm.exe' with args: 'exist oei noref dbe cm ion=[M+H]+ ppm=5.000000 el=CHNOPSCl het ms=C:\Users\167160\AppData\Local\Temp\Rtmp0EPclk\MSPList2a7c704718b1.txt m=736.136658 out=C:\Users\167160\AppData\Local\Temp\Rtmp0EPclk\formulas2a7c6265a70.txt'. Exit code: 1

So I tried to add some complementary arguments to the function (oei, dbe and cm) which were asked to be put in as a list of character, so I tried to run : 

`formulas <- generateFormulas(fGroupsopenms, "genform", plists,
                             adduct = "[M+H]+", elements = "CHNOPSCl", 
                             extraOpts = list(as.character("oei", "dbe" ,"cm")))`

And this error came : 

> Error in generateFormulas(fGroupsopenms, "genform", plists, adduct = "[M+H]+",  : 
  1 assertions failed:
  Variable 'extraOpts': Vector must be named, but is NULL

When trying to run the same command by changing extraOpts into extraOpts = NULL, I have the first error message again.
Do you have a clue on how to solve this issue? I tried to look for more information about genform but I didn't find how to write the extraOpts argument in the right way.
Anyway, thank you for your work and thank you in advance for your answer,

Nina

**Comment by rickhelmus** [comment]
Hi Nina,

Thanks for your bug report!

There seem to be two things going on:
1. GenForm fails for mysterious reasons.
2. the generateFormulas() function handled checking the extraOpts argument wrong. I just fixed this now and pushed it to GitHub. Taking your example, the format should be `extraOpts = c("oei", "dbe" ,"cm")`.

As for (1), I hope you can help me a little bit with debugging. Some things to try are:
a. I recently modified code that runs GenForm in parallel. Can you try re-running it without parallelisation? In this case set `maxProcAmount` and `batchSize` to `1`, e.g. 
`formulas <- generateFormulas(fGroupsopenms, "genform", plists, maxMzDev = 5, adduct = "[M+H]+", elements = "CHNOPSCl", maxProcAmount = 1, batchSize = 1)`
b. Can you run GenForm manually? This might show more error information. You can do so by opening a command shell (or from the 'Terminal' tab if you have a recent/preview RStudio version). The command to run can be deduced from your first error, e.g.
`'C:/Users/167160/Documents/R/R-3.5.3/library/patRoon/bin//x64/GenForm.exe' exist oei noref dbe cm ion=[M+H]+ ppm=5.000000 el=CHNOPSCl het ms=C:\Users\167160\AppData\Local\Temp\Rtmp0EPclk\MSPList2a7c704718b1.txt m=736.136658 out=C:\Users\167160\AppData\Local\Temp\Rtmp0EPclk\formulas2a7c6265a70.txt'`
Note that this command involves some temporary files. You may need to re-run the generateFormulas() function again (and let it fail again) to re-generate the temporary files (which then will be differently named).
c. Perhaps you can try the binary package. I still need to document this, but you can do so by installing it with:
`install.packages("patRoon", repos = "https://rickhelmus.github.io/patRoonDeps/", type = "binary")`

Thanks,
Rick

**Comment by nina-huynh** [comment]
Hi Rick,

Thanks for your fast answer.

I tried solution a) which gives me an error stating that batchsize was an unused argument so I remove it and run the command again and the second error message from my previous post appears again.
So I tried solution b) which gives me this error : 
>  unknown adduct type '[M+H]+'
So I removed it and it worked. I came back to the console and run the command a little bit differently : 
`formulas` <- generateFormulas(fGroupsopenms, "genform", plists, maxMzDev = 5, elements = "CHNOPSCl")
And it worked very well!
Also, I tried to replace   adduct = "[M+H]+"   by   ion=M+H  (which I found in the description of GenForm arguments) and it seems to work!

Thank you again,

Nina

**Comment by rickhelmus** [comment]
Great!

My guess is that your current version of patRoon is a bit 'old' as I changed some of these things recently. Of course no problem if it works! :-) However if you run in another error it might help if you update patRoon.

Cheers,
Rick
