### ISSUE TITLE
MetaClean package deprecated

### ISSUE THREAD

**Issue by tsufz** [rickhelmus/patRoon#81]
Hi Rick,
The [`MetaClean`](https://cran.r-project.org/web/packages/MetaClean/index.html) package was deprecated some while ago (as it's dependencies `scmamp` and `fastADAboost`) as they are stalled for some while (several years). Thus, for a non experienced user, it is impossible to compile all the sources and to install patRoon properly. Please consider removing the dependency on `MetaClean`.

Yours
Tobias

**Comment by rickhelmus** [comment]
Hi Tobias,

Thanks for the heads-up! I did notice that `fastADABoost` was removed, as a work around you can either install it from GitHub or MRAN, e.g. this is what I do with CI

```r
remotes::install_github("souravc83/fastAdaboost")
install.packages('fastAdaboost', repos = 'https://mran.revolutionanalytics.com/snapshot/2022-07-01')
```

My hope was that fastADABoost would come back, but that doesn't seem to be the case as you mentioned.

I didn't notice `scmamp` though, will check that out.

Note that `MetaClean` is an optional dependency, so it shouldn't cause issues for the `patRoon` installation. In any case, I will upload the documentation for this.

**Comment by tsufz** [comment]
Hi Rick,
Yes, thanks for the update!

Best
Tobias

**Comment by rickhelmus** [comment]
The new installation procedure/docs handle this better now, so I think this can be closed.
