### ISSUE TITLE
Update link to OpenBabel

### ISSUE THREAD

**Issue by tsufz** [rickhelmus/patRoon#82]
Hi Rick,
The [manual](https://rickhelmus.github.io/patRoon/handbook_bd/manual-installation.html) links to the outdated homepage of [OpenBabel](https://openbabel.org/wiki/Main_Page). This page is not maintained any more, and I suggest linking to the [GitHub page of OpenBabel](https://github.com/openbabel/openbabel/releases).

Yours
Tobias

**Comment by rickhelmus** [comment]
Hi Tobias,

Thanks! Just updated the URL.
