### ISSUE TITLE
Error in (function (classes, fdef, mtable)

### ISSUE THREAD

**Issue by TantawiOmar** [rickhelmus/patRoon#83]
Hello Rick, 

I am Omar, a PhD student in Environmental Engineering. I am trying to use patRoon to analyze some LC HRMS data and it is working well. However, I am trying to use "nontarget" algorithm to generate homologous series and "TP" algorithm to generate transformation products. Everything executes well and the code prompt back that X number of features were linked. However, if I check the datafiles, the links columns are always empty. Do you have any recommendations on why this is happening and how to resolve it? 

Thanks for all your help. I truly very much appreciate it! 

Best, 
Omar

**Comment by rickhelmus** [comment]
Hi Omar,

The `links` column is actually only used to store information about 'conflicts'. For NT this is explained further in [the handbook](https://rickhelmus.github.io/patRoon/handbook_bd/componentization.html#homologues-series). For TP components, it means that a certain TP was found in multiple components. This is fairly rare, but could happen if, for instance, if a certain parent suspect was assigned to multiple features during suspect screening. In hindsight, maybe the name of the `links` column wasn't a good choice, especially now with TP componentization.

In any case, the links column is probably not what you are after. Instead, the components tell you which feature groups 'belong' to each other. For NT, each component is a candidate homologous series, while each TP component consists of the TPs for a certain parent. The handbook has more information on inspecting the results, e.g. https://rickhelmus.github.io/patRoon/handbook_bd/inspecting-results.html. The `componentInfo()` function can be used to get information on the parents. Furthermore, the [reporting functionality](https://rickhelmus.github.io/patRoon/handbook_bd/report.html) can be used to easily get an overview for all of this.

Hopefully this helps a bit ;-)

Thanks,
Rick

**Comment by rickhelmus** [comment]
Closed due to inactivity, feel free to re-open!
