### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by mingw86** [rickhelmus/patRoon#86]
Dear developers,
I’ve been struggling with installing PatRoon, I ran below command in RStudio
“install_zip_gh("rickhelmus/patRoon")”
However, there are always some errors, please help!
Many thanks!
ming

attached is R seession and error
![seession](https://github.com/rickhelmus/patRoon/assets/137246849/60cd4810-3ab8-467d-88bc-130f02a3dba9)
![error](https://github.com/rickhelmus/patRoon/assets/137246849/3b9e7474-cce6-4925-a727-4c4648b81473)

**Comment by mingw86** [comment]
sry for the wrong install code: I typed :
remotes::install_github("rickhelmus/patRoon")

**Comment by rickhelmus** [comment]
Closed due to inactivity, feel free to re-open!
