### ISSUE TITLE
loadMSLibrary "Error: stod"

### ISSUE THREAD

**Issue by drewszabo** [rickhelmus/patRoon#88]
Hey Rick,

Sorry to raise another issue so soon. I'm not sure if this is related to the patch you just pushed the other day. But I can't seem to load the MassBank .msp library using the loadMSLibrary() function. Receiving `Error: stod`. I cant find any documentation about this particular error. I'm sorry that I can't be any further help troubleshooting this one.

Cheers,

**Comment by rickhelmus** [comment]
Seems I introduced a small bug while working on #72. Hopefully it's fixed now.

Thanks for the report (again!).

**Comment by drewszabo** [comment]
Fantastic. Working on my end now. Cheers,
