### ISSUE TITLE
Load a previous group features list

### ISSUE THREAD

**Issue by Boris-Droz** [rickhelmus/patRoon#94]
Hi Rick,
Is it possible to load an existing feature list previously save in a text file (csv or txt) in patRoon to performed further analysis? Some of my collaborator made some suspect analysis on MSDial and ask me if I could do the Metabologic analysis you recently implement in PatRoon. I want to start with the same feature list, if it is possible. Thank you.

**Comment by rickhelmus** [comment]
Hi Boris,

This is something I'm planning to add for the next major release, scheduled for next year. However, a possible workaround now might be to convert your data as a Bruker TASQ CSV file and import it with the [importFeatureGroupsBrukerTASQ()](https://rickhelmus.github.io/patRoon/reference/importFeatureGroupsBrukerTASQ.html) function. An example file is found [here](https://github.com/rickhelmus/patRoon/blob/master/tests/testthat/test_data_sets/GlobalResults-TASQ-pos.csv).

Only the following columns are used:

```r
> patRoon:::TASQImportCols()
[1] "V1"           "Data Set"     "Analyte Name" "RT [min]"     "m/z meas."    "Height of PI" "Area of PI"   "FWHM [s]
```

For the `Analyte Name` you should take a unique name that is the same for features across analyses (i.e. feature group). The `FWHM [s]` column is used to calculate peak widths, which are mainly used for plotting chromatograms.

Hope this can help!

Rick

**Comment by Boris-Droz** [comment]
Great, thank you very much it work perfectly.
